# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05bd0f54f374e231e0abffb79f0050f8ddfa642b79d19ac45ab9eaf2b050c130619f8926ffd034c1fbecf8e50f81e2488d9613ddaee6afdf0deba44a3b325959

test:
  secret_key_base: d8497590c2385ae9b4bc2da0aefafb8d7482bc2c2f8d5d33e9a49aa6eeb1d2efb2b479e6174a29c6847428adb16cca1fb52245f728c45cb36e6cf88b6499d2d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
